@baseUrl = http://localhost:3333

# @name create_individual_account
POST {{baseUrl}}/clients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@test.com",
  "document": "39920111007",
  "password": "123456"
}

###

# @name create_company_account
POST {{baseUrl}}/clients
Content-Type: application/json

{
  "name": "John Doe Corp",
  "email": "john.doe.corp@test.com",
  "document": "82740720000158",
  "password": "123456",
  "type": "COMPANY"
}

###

# @name create_transfer
POST {{baseUrl}}/transfers
Content-Type: application/json

{
  "senderId": "e16fa6db-f2de-44b8-bd88-f1db49e11737",
  "recipientId": "cda43062-47b6-4a9c-ab7f-fa9bf5c9976d",
  "amount": 100,
  "description": "compra uma chocolate"
}

###
# @name reverse_transfer
POST {{baseUrl}}/transfers/reverse
Content-Type: application/json

{
  "id": "01HRTJN25WEBQW67H77ZF39TKD"
}

###