@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/clients
Content-Type: application/json

{
  "name": "John Doe 2",
  "email": "john.doe2@test.com",
  "document": "74974644009",
  "password": "123456"
}

###

