version: '3.8'

services:
  postgres:
    container_name: wallet-challenge-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: wallet-challenge
      PGDATA: /data/postgres

  wallet_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_api
    environment:
      - PORT=3333
    ports:
      - '3333:3333'
    depends_on:
      - postgres