version: '3.0'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: wallet-challenge
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  wallet_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3333
    ports:
      - "3333:3333"
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: "sh start.sh"